name:                curvy-utils
github:              "1in1/Curvy-Utils"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stack-template#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- integer-roots
- lens
- arithmoi
- ad

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions: 
    - DataKinds
    - KindSignatures
    - NoFieldSelectors
    - ScopedTypeVariables
    - OverloadedRecordDot

tests:
  curvy-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - QuickCheck
    - curvy-utils
    - lens
    default-extensions: ScopedTypeVariables, KindSignatures, DataKinds
